networks:
  plane-net:

services:
  web:
    container_name: web
    networks:
      - plane-net
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.web
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    depends_on:
      - api

  admin:
    container_name: admin
    networks:
      - plane-net
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.admin
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    depends_on:
      - api
      - web

  space:
    container_name: space
    networks:
      - plane-net
    build:
      context: .
      dockerfile: ./apps/space/Dockerfile.space
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    depends_on:
      - api
      - web

  api:
    container_name: api
    networks:
      - plane-net
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    command: ./bin/docker-entrypoint-api.sh
    environment:
      DEBUG: ${DEBUG:-0}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT:-6379}/
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      SIGNED_URL_EXPIRATION: ${SIGNED_URL_EXPIRATION:-3600}
      DOCKERIZED: ${DOCKERIZED:-1}
      USE_MINIO: ${USE_MINIO:-0}
      WEB_URL: ${WEB_URL}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
      ADMIN_BASE_PATH: ${ADMIN_BASE_PATH:-/god-mode}
      SPACE_BASE_URL: ${SPACE_BASE_URL}
      SPACE_BASE_PATH: ${SPACE_BASE_PATH:-/spaces}
      APP_BASE_URL: ${APP_BASE_URL}
      APP_BASE_PATH: ${APP_BASE_PATH:-}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH:-/live}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      HARD_DELETE_AFTER_DAYS: ${HARD_DELETE_AFTER_DAYS:-60}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL:-0}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT:-60/minute}
    depends_on:
      - plane-db
      - plane-redis

  worker:
    container_name: bgworker
    networks:
      - plane-net
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    command: ./bin/docker-entrypoint-worker.sh
    environment:
      DEBUG: ${DEBUG:-0}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT:-6379}/
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      SIGNED_URL_EXPIRATION: ${SIGNED_URL_EXPIRATION:-3600}
      DOCKERIZED: ${DOCKERIZED:-1}
      USE_MINIO: ${USE_MINIO:-0}
      WEB_URL: ${WEB_URL}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
      ADMIN_BASE_PATH: ${ADMIN_BASE_PATH:-/god-mode}
      SPACE_BASE_URL: ${SPACE_BASE_URL}
      SPACE_BASE_PATH: ${SPACE_BASE_PATH:-/spaces}
      APP_BASE_URL: ${APP_BASE_URL}
      APP_BASE_PATH: ${APP_BASE_PATH:-}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH:-/live}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      HARD_DELETE_AFTER_DAYS: ${HARD_DELETE_AFTER_DAYS:-60}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL:-0}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT:-60/minute}
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    container_name: beatworker
    networks:
      - plane-net
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    command: ./bin/docker-entrypoint-beat.sh
    environment:
      DEBUG: ${DEBUG:-0}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT:-6379}/
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      SIGNED_URL_EXPIRATION: ${SIGNED_URL_EXPIRATION:-3600}
      DOCKERIZED: ${DOCKERIZED:-1}
      USE_MINIO: ${USE_MINIO:-0}
      WEB_URL: ${WEB_URL}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
      ADMIN_BASE_PATH: ${ADMIN_BASE_PATH:-/god-mode}
      SPACE_BASE_URL: ${SPACE_BASE_URL}
      SPACE_BASE_PATH: ${SPACE_BASE_PATH:-/spaces}
      APP_BASE_URL: ${APP_BASE_URL}
      APP_BASE_PATH: ${APP_BASE_PATH:-}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH:-/live}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      HARD_DELETE_AFTER_DAYS: ${HARD_DELETE_AFTER_DAYS:-60}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL:-0}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT:-60/minute}
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    container_name: plane-migrator
    networks:
      - plane-net
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
      args:
        DOCKER_BUILDKIT: 1
    restart: no
    command: ./bin/docker-entrypoint-migrator.sh
    environment:
      DEBUG: ${DEBUG:-0}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT:-6379}/
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      SIGNED_URL_EXPIRATION: ${SIGNED_URL_EXPIRATION:-3600}
      DOCKERIZED: ${DOCKERIZED:-1}
      USE_MINIO: ${USE_MINIO:-0}
      WEB_URL: ${WEB_URL}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
      ADMIN_BASE_PATH: ${ADMIN_BASE_PATH:-/god-mode}
      SPACE_BASE_URL: ${SPACE_BASE_URL}
      SPACE_BASE_PATH: ${SPACE_BASE_PATH:-/spaces}
      APP_BASE_URL: ${APP_BASE_URL}
      APP_BASE_PATH: ${APP_BASE_PATH:-}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH:-/live}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      HARD_DELETE_AFTER_DAYS: ${HARD_DELETE_AFTER_DAYS:-60}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL:-0}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT:-60/minute}
    depends_on:
      - plane-db
      - plane-redis

  live:
    container_name: plane-live
    networks:
      - plane-net
    build:
      context: .
      dockerfile: ./apps/live/Dockerfile.live
      args:
        DOCKER_BUILDKIT: 1
    restart: always

  plane-db:
    container_name: plane-db
    networks:
      - plane-net
    image: postgres:15.7-alpine
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data

  plane-redis:
    container_name: plane-redis
    networks:
      - plane-net
    image: valkey/valkey:7.2.11-alpine
    restart: always
    volumes:
      - redisdata:/data

  plane-mq:
    container_name: plane-mq
    networks:
      - plane-net
    image: rabbitmq:3.13.6-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  plane-minio:
    container_name: plane-minio
    networks:
      - plane-net
    image: minio/minio
    restart: always
    command: server /export --console-address ":9090"
    volumes:
      - uploads:/export
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}

  proxy:
    container_name: proxy
    networks:
      - plane-net
    build:
      context: ./apps/proxy
      dockerfile: Dockerfile.ce
    restart: always
    environment:
      SITE_ADDRESS: ":80"
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
    depends_on:
      - web
      - api
      - space
      - admin

volumes:
  pgdata:
  redisdata:
  uploads:
  rabbitmq_data:
